[package]
name = "trusted_model"
version = "0.1.0"
authors = ["people"]

[dependencies]
trusted_pal = { path = "../pal" }
raft = { path = "../../"}
prost = { version = "0.11", default-features = false, features = ["prost-derive"] }